version: '3.4'

services:
  catalogueDb:
    image: mongo
  basketDb:
    image: redis:alpine
  discountsDatabase:
    image: postgres:latest
  pgadmin:
    image: dpage/pgadmin4
  portainer:
    image: portainer/portainer-ce
  
  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  #discount.api:
  #  image: ${DOCKER_REGISTRY-}discountapi
  #  build:
  #    context: .
  #    dockerfile: Services/Discount/Discount.API/Dockerfile

  discounts.api:
    image: ${DOCKER_REGISTRY-}discountsapi
    build:
      context: .
      dockerfile: Services/Discount/Discounts.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:



