version: '3.4'

services:
  catalogueDb:
    image: mongo
  basketDb:
    image: redis:alpine
  discountDb:
    image: postgres
  pgadmin:
    image: dpage/pgadmin
  portainer:
    image: portainer/portainer-ce
  
  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

