version: '3.4'

services:
  catalogueDb:
    container_name: catalogueDb
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - mongo_data/data/db

  basketDb:
    container_name: basketDb
    restart: always
    ports:
    - "6379:6379"

  discountsDatabase:
    container_name: discountsDatabase
    environment:
     - POSTGRES_USER=minister
     - POSTGRES_PASSWORD=admin12345678
     - POSTGRES_DB=DiscountsDatabase_1
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=administrator@microservices.com
      - PGADMIN_DEFAULT_PASSWORD=admin12345
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
    - "8080:8000"
    - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    
  
  catalogue.api:
    container_name: Catalogue.API

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogueDb:27017"
    depends_on:
      - catalogueDb
    ports:
      - "8000:80"
  
  basket.api:
    container_name: Basket.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketDb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketDb
    ports:
      - "8001:80"

  discounts.api:
    container_name: Discount.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=discountsDatabase;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;"
    depends_on:
      - discountsDatabase
    ports:
      - "8002:80"


  discounts.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
       - "ConnectionStrings:DefaultConnection=Server=discountsDatabase;Port=5432;Database=DiscountDb;User Id=admin;Password=admin12345;"
    ports:
      - "8003:80"

